require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "SidebarNavigation-1.8.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Sidebar Navigation" \
		--summary="An easy to use and versatile slideout menu." \
		--publisher="Jack Dehlin" \
		--website="https://github.com/jdehlin/Xamarin-Sidebar" \
		--publisher-url="https://github.com/jdehlin/Xamarin-Sidebar" \
		--details="Details.md" \
		--license="../LICENSE.md" \
		--getting-started="GettingStarted.md" \
		--icon="SidebarNavigation_128x128.png" \
		--icon="SidebarNavigation_512x512.png" \
		--library="ios":"../Xamarin-Sidebar/bin/Release/Xamarin-Sidebar.dll" \
		--library="ios-unified":"../Xamarin-Sidebar-Unified/bin/Release/Xamarin-Sidebar-Unified.dll" \
		--sample="A simple sample. In this simple sample the menu buttons replace the content view. ":"samples/SimpleSample/SimpleSample.sln" \
		--sample="A navigation sample. In this sample the the menu buttons push views onto a navigation controller.":"samples/NavigationSample/NavigationSample.sln" \
		--sample="A simple Unified API sample. In this simple sample the menu buttons replace the content view. ":"samples/UnifiedSample/UnifiedSample.sln" \
		--sample="A navigation Unified API sample. In this sample the the menu buttons push views onto a navigation controller.":"samples/NavigationUnifiedSample/NavigationUnifiedSample.sln" 
		
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
