require "rake/clean"



CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "Xamarin-Sidebar-0.5.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o -q xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="Xamarin Sidebar" \
		--summary="An easy to use and versatile slideout menu." \
		--publisher="Jack Dehlin" \
		--website="https://github.com/jdehlin/Xamarin-Sidebar" \
		--publisher-url="https://github.com/jdehlin/Xamarin-Sidebar" \
		--details="Details.md" \
		--license="../LICENSE.md" \
		--getting-started="GettingStarted.md" \
		--icon="Xamarin-Sidebar_128x128.png" \
		--icon="Xamarin-Sidebar_512x512.png" \
		--library="ios":"../Xamarin-Sidebar/bin/Release/Xamarin-Sidebar.dll" \
		--sample="A simple and navigation sample. In the simple sample the menu buttons replace the content view. In the navigation controller the menu buttons push views onto the navigation controller.":"../Xamarin-Sidebar.sln"
		
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
